### PR TITLE
Fix test_mixer fails on local build

### LINKED ISSUE #314: Test mixer fails locally with latest version
Test output:

aespinoza-23506:achronopoulos[~/repos/cubeb_project/cubeb-build]$./test_mixer 
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from cubeb
[ RUN      ] cubeb.mixer
Downmix from dual mono to undefined
Downmix from dual mono to mono
Downmix from dual mono lfe to undefined
Downmix from dual mono lfe to dual mono
Downmix from dual mono lfe to mono
Downmix from dual mono lfe to mono lfe
Downmix from dual mono lfe to stereo
Downmix from mono to undefined
Downmix from mono lfe to undefined
Downmix from mono lfe to mono
Downmix from stereo to undefined
Downmix from stereo to mono
Downmix from stereo lfe to undefined
Downmix from stereo lfe to dual mono
Downmix from stereo lfe to mono
Downmix from stereo lfe to mono lfe
Downmix from stereo lfe to stereo
Downmix from 3f to undefined
Downmix from 3f to dual mono
Downmix from 3f to mono
Downmix from 3f to mono lfe
Downmix from 3f to stereo
Downmix from 3f lfe to undefined
Downmix from 3f lfe to dual mono
Downmix from 3f lfe to dual mono lfe
Downmix from 3f lfe to mono
Downmix from 3f lfe to mono lfe
Downmix from 3f lfe to stereo
Downmix from 3f lfe to stereo lfe
Downmix from 3f lfe to 3f
Downmix from 3f lfe to 2f1
Downmix from 2f1 to undefined
Downmix from 2f1 to dual mono
Downmix from 2f1 to mono
Downmix from 2f1 to mono lfe
Downmix from 2f1 to stereo
Downmix from 2f1 lfe to undefined
Downmix from 2f1 lfe to dual mono
Downmix from 2f1 lfe to dual mono lfe
Downmix from 2f1 lfe to mono
Downmix from 2f1 lfe to mono lfe
Downmix from 2f1 lfe to stereo
Downmix from 2f1 lfe to stereo lfe
Downmix from 2f1 lfe to 3f
Downmix from 2f1 lfe to 2f1
Downmix from 3f1 to undefined
Downmix from 3f1 to dual mono
Downmix from 3f1 to dual mono lfe
Downmix from 3f1 to mono
Downmix from 3f1 to mono lfe
Downmix from 3f1 to stereo
Downmix from 3f1 to stereo lfe
Downmix from 3f1 to 3f
Downmix from 3f1 to 2f1
Downmix from 3f1 lfe to undefined
Downmix from 3f1 lfe to dual mono
Downmix from 3f1 lfe to dual mono lfe
Downmix from 3f1 lfe to mono
Downmix from 3f1 lfe to mono lfe
Downmix from 3f1 lfe to stereo
Downmix from 3f1 lfe to stereo lfe
Downmix from 3f1 lfe to 3f
Downmix from 3f1 lfe to 3f lfe
Downmix from 3f1 lfe to 2f1
Downmix from 3f1 lfe to 2f1 lfe
Downmix from 3f1 lfe to 3f1
Downmix from 3f1 lfe to 2f2
Downmix from 2f2 to undefined
Downmix from 2f2 to dual mono
Downmix from 2f2 to dual mono lfe
Downmix from 2f2 to mono
Downmix from 2f2 to mono lfe
Downmix from 2f2 to stereo
Downmix from 2f2 to stereo lfe
Downmix from 2f2 to 3f
Downmix from 2f2 to 2f1
Downmix from 2f2 lfe to undefined
Downmix from 2f2 lfe to dual mono
Downmix from 2f2 lfe to dual mono lfe
Downmix from 2f2 lfe to mono
Downmix from 2f2 lfe to mono lfe
Downmix from 2f2 lfe to stereo
Downmix from 2f2 lfe to stereo lfe
Downmix from 2f2 lfe to 3f
Downmix from 2f2 lfe to 3f lfe
Downmix from 2f2 lfe to 2f1
Downmix from 2f2 lfe to 2f1 lfe
Downmix from 2f2 lfe to 3f1
Downmix from 2f2 lfe to 2f2
Downmix from 3f2 to undefined
Downmix from 3f2 to dual mono
Downmix from 3f2 to dual mono lfe
Downmix from 3f2 to mono
[3f2] Expect: 13.035530, Get: 13.035530
[3f2] Expect: 13.035530, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 13.0355
Downmix from 3f2 to mono lfe
[3f2] Expect: 13.035530, Get: 13.035530
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 13.035530, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 13.0355
Downmix from 3f2 to stereo
[3f2] Expect: 8.363955, Get: 8.363955
[3f2] Expect: 10.071060, Get: 10.071060
[3f2] Expect: 8.363955, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 8.36395
Downmix from 3f2 to stereo lfe
[3f2] Expect: 8.363955, Get: 8.363955
[3f2] Expect: 10.071060, Get: 10.071060
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 8.363955, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 8.36395
Downmix from 3f2 to 3f
[3f2] Expect: 5.535530, Get: 5.535530
[3f2] Expect: 7.242636, Get: 7.242636
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 5.535530, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 5.53553
Downmix from 3f2 to 3f lfe
[3f2] Expect: 5.535530, Get: 5.535530
[3f2] Expect: 7.242636, Get: 7.242636
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.535530, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 5.53553
Downmix from 3f2 to 2f1
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 4.828424, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 4.82842
Downmix from 3f2 to 2f1 lfe
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 4.828424, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 4.82842
Downmix from 3f2 to 3f1
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 2
Downmix from 3f2 to 3f1 lfe
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 7.778166, Get: 7.778166
Downmix from 3f2 to 2f2
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 4.82842
Downmix from 3f2 to 2f2 lfe
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 0.000000, Get: 0.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
Downmix from 3f2 lfe to undefined
Downmix from 3f2 lfe to dual mono
Downmix from 3f2 lfe to dual mono lfe
Downmix from 3f2 lfe to mono
[3f2] Expect: 13.035530, Get: 13.035530
[3f2] Expect: 13.035530, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 13.0355
Downmix from 3f2 lfe to mono lfe
[3f2] Expect: 13.035530, Get: 13.035530
[3f2] Expect: 10.000000, Get: 10.000000
[3f2] Expect: 13.035530, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 13.0355
Downmix from 3f2 lfe to stereo
[3f2] Expect: 8.363955, Get: 8.363955
[3f2] Expect: 10.071060, Get: 10.071060
[3f2] Expect: 8.363955, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 8.36395
Downmix from 3f2 lfe to stereo lfe
[3f2] Expect: 8.363955, Get: 8.363955
[3f2] Expect: 10.071060, Get: 10.071060
[3f2] Expect: 10.000000, Get: 10.000000
[3f2] Expect: 8.363955, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 8.36395
Downmix from 3f2 lfe to 3f
[3f2] Expect: 5.535530, Get: 5.535530
[3f2] Expect: 7.242636, Get: 7.242636
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 5.535530, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 5.53553
Downmix from 3f2 lfe to 3f lfe
[3f2] Expect: 5.535530, Get: 5.535530
[3f2] Expect: 7.242636, Get: 7.242636
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 10.000000, Get: 10.000000
[3f2] Expect: 5.535530, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 5.53553
Downmix from 3f2 lfe to 2f1
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 4.828424, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 4.82842
Downmix from 3f2 lfe to 2f1 lfe
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 10.000000, Get: 10.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 4.828424, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 4.82842
Downmix from 3f2 lfe to 3f1
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 2
Downmix from 3f2 lfe to 3f1 lfe
[3f2] Expect: 2.000000, Get: 2.000000
[3f2] Expect: 3.000000, Get: 3.000000
[3f2] Expect: 4.000000, Get: 4.000000
[3f2] Expect: 10.000000, Get: 10.000000
[3f2] Expect: 7.778166, Get: 7.778166
[3f2] Expect: 2.000000, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 2
Downmix from 3f2 lfe to 2f2
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 4.82842
Downmix from 3f2 lfe to 2f2 lfe
[3f2] Expect: 4.828424, Get: 4.828424
[3f2] Expect: 5.828424, Get: 5.828424
[3f2] Expect: 10.000000, Get: 10.000000
[3f2] Expect: 5.000000, Get: 5.000000
[3f2] Expect: 6.000000, Get: 6.000000
[3f2] Expect: 4.828424, Get: 0.000000
cubeb_project/cubeb/test/test_mixer.cpp:169: Failure
Value of: out[i]
  Actual: 0
Expected: downmix_results[index]
Which is: 4.82842
Downmix from 3f2 lfe to 3f2
Downmix from 3f3r lfe to undefined
Downmix from 3f3r lfe to dual mono
Downmix from 3f3r lfe to dual mono lfe
Downmix from 3f3r lfe to mono
Downmix from 3f3r lfe to mono lfe
Downmix from 3f3r lfe to stereo
Downmix from 3f3r lfe to stereo lfe
Downmix from 3f3r lfe to 3f
Downmix from 3f3r lfe to 3f lfe
Downmix from 3f3r lfe to 2f1
Downmix from 3f3r lfe to 2f1 lfe
Downmix from 3f3r lfe to 3f1
Downmix from 3f3r lfe to 3f1 lfe
Downmix from 3f3r lfe to 2f2
Downmix from 3f3r lfe to 2f2 lfe
Downmix from 3f3r lfe to 3f2
Downmix from 3f3r lfe to 3f2 lfe
Downmix from 3f4 lfe to undefined
Downmix from 3f4 lfe to dual mono
Downmix from 3f4 lfe to dual mono lfe
Downmix from 3f4 lfe to mono
Downmix from 3f4 lfe to mono lfe
Downmix from 3f4 lfe to stereo
Downmix from 3f4 lfe to stereo lfe
Downmix from 3f4 lfe to 3f
Downmix from 3f4 lfe to 3f lfe
Downmix from 3f4 lfe to 2f1
Downmix from 3f4 lfe to 2f1 lfe
Downmix from 3f4 lfe to 3f1
Downmix from 3f4 lfe to 3f1 lfe
Downmix from 3f4 lfe to 2f2
Downmix from 3f4 lfe to 2f2 lfe
Downmix from 3f4 lfe to 3f2
Downmix from 3f4 lfe to 3f2 lfe
Downmix from 3f4 lfe to 3f3r lfe
[  FAILED  ] cubeb.mixer (2 ms)
[----------] 1 test from cubeb (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] cubeb.mixer

 1 FAILED TEST

### PR DESCRIPTION
**Pull request by ChunMinChang**
- Fix #314 
- Fix warnings of comparison of integers of different signs
- Add debugging messages

### CODE REVIEW

File: test/common.h [hunk 1]
```diff
@@ -68,6 +69,20 @@ layout_info const layout_infos[CUBEB_LAYOUT_MAX] = {
...
+  "center",                 // CHANNEL_CENTER
+  "left surround",          // CHANNEL_LS
+  "right surround",         // CHANNEL_RS
+  "rear left surround",     // CHANNEL_RLS
+  "rear center",            // CHANNEL_RCENTER
+  "rear right surround",    // CHANNEL_RRS
+  "low frequency effects",  // CHANNEL_LFE
+  "unmapped"                // CHANNEL_UNMAPPED
+};
+
```
Comment (achronop) [inline test/common.h]: Since for now this is only used by `test_mixer.cpp` why do you add it here (and include also a new header) and not in the test file? In any case it's not that big of a deal.

File: test/test_mixer.cpp [hunk 2]
```diff
@@ -158,33 +159,45 @@ downmix_test(float const * data, cubeb_channel_layout in_layout, cubeb_channel_l
     out_layout_mask |= 1 << CHANNEL_INDEX_TO_ORDER[out_layout][i];
   }
 
-  for (unsigned int i = 0 ; i < inframes * out_params.channels ; ++i) {
+  for (unsigned int i = 0 ; i < out.size() ; ++i) {
+    assert(in_params.channels && out_params.channels);
```
Comment (ChunMinChang) [inline test/test_mixer.cpp]: It's used to pass the scan-build warning: Division by zero
```
/home/travis/build/kinetiknz/cubeb/test/test_mixer.cpp:188:28: warning: Division by zero

    unsigned int index = i % out_params.channels;

                         ~~^~~~~~~~~~~~~~~~~~~~~

1 warning generated.

https://travis-ci.org/kinetiknz/cubeb/builds/238646995?utm_source=github_status&utm_medium=notification
https://travis-ci.org/kinetiknz/cubeb/jobs/238647001
```
